In [2]:
import pandas as pd

In [3]:
df = pd.read_excel("medical_person.xlsx")
df

,지역,인력코드상위,의사,의사.1,의사.2,의사.3,의사.4,치과의사,치과의사.1,치과의사.2,한의사,한의사.1,한의사.2,한의사.3,조산사,약사계,물리치료사,작업치료사,사회복지사
0,시도,요양기관종별,의사계,일반의,인턴,레지던트,전문의,치과의사계,치과일반의,치과전문의,한의사계,한의사일반의,한의사일반수련의,한의사전문의,조산사,약사계,물리치료사,작업치료사,사회복지사
1,서울,병원,2074,43,-,27,2004,35,15,20,35,17,3,15,3,257,1847,557,67
2,부산,병원,1029,16,-,3,1010,3,2,1,12,8,1,3,-,137,1089,391,36
3,인천,병원,509,6,-,3,500,4,1,3,11,8,-,3,-,54,686,250,23
4,대구,병원,694,16,1,3,674,4,3,1,7,5,1,1,-,90,915,445,24
5,광주,병원,499,2,-,-,497,-,-,-,12,9,-,3,-,65,454,180,15
6,대전,병원,412,5,-,-,407,2,1,1,3,1,-,2,-,39,464,202,15
7,울산,병원,207,5,-,-,202,1,1,-,4,3,-,1,-,31,171,52,4
8,경기,병원,2360,41,-,5,2314,36,6,30,25,19,2,4,8,250,2427,887,106
9,강원,병원,260,10,-,-,250,21,3,18,1,1,-,-,-,29,263,99,14
10,충북,병원,252,6,-,-,246,7,2,5,2,-,-,2,-,34,280,139,14
11,충남,병원,319,10,-,-,309,3,-,3,3,2,-,1,-,40,294,103,11
12,전북,병원,279,7,-,-,272,1,1,-,5,4,-,1,-,48,298,81,10
13,전남,병원,459,14,1,-,444,3,2,1,3,1,-,2,-,62,318,58,12
14,경북,병원,341,8,-,-,333,7,-,7,4,4,-,-,-,37,371,115,16
15,경남,병원,789,15,-,-,774,13,3,10,11,9,-,2,3,127,815,240,19
16,제주,병원,42,-,-,-,42,-,-,-,0,0,-,-,-,8,81,39,5
17,세종,병원,16,-,-,-,16,-,-,-,-,-,-,-,1,3,5,-,-

In [13]:
import pandas as pd

# 데이터 파일을 DataFrame으로 불러옵니다. 여기서는 파일이 'data.csv'라고 가정합니다.
# 파일 형식이 다르다면, pd.read_excel 등 다른 함수를 사용해야 할 수 있습니다.
df = pd.read_excel('medical_person.xlsx')

# '지역' 열에서 '서울'인 행을 선택합니다.

In [14]:
seoul_row = df[df['지역'] == '서울']

# 서울 행을 출력합니다.
print(seoul_row)

   지역 인력코드상위    의사 의사.1 의사.2 의사.3  의사.4 치과의사 치과의사.1 치과의사.2 한의사 한의사.1 한의사.2  \
1  서울     병원  2074   43    -   27  2004   35     15     20  35    17     3

  한의사.3 조산사  약사계 물리치료사 작업치료사 사회복지사
1    15   3  257  1847   557    67

In [20]:
import streamlit as st
import pandas as pd

# 제목 설정
st.title('지역별 의사 수 시각화')

# Excel 파일 로드
df = pd.read_excel('test_2.xlsx')

# 데이터 확인을 위한 테이블 표시
st.write("지역별 의사 수 데이터", df)

# 간단한 바 차트로 시각화
st.bar_chart(df.set_index('지역')['의사'])

2024-03-15 16:04:54.251 Serialization of dataframe to Arrow table was unsuccessful due to: ("Expected bytes, got a 'int' object", 'Conversion failed for column 의사 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.

2024-03-15 16:04:54.335 Serialization of dataframe to Arrow table was unsuccessful due to: ("Expected bytes, got a 'int' object", 'Conversion failed for column 의사 with type object'). Applying automatic fixes for column types to make the dataframe Arrow-compatible.

DeltaGenerator()